// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: cluster.proto

package cluster

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for TiCPClusterService service

func NewTiCPClusterServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for TiCPClusterService service

type TiCPClusterService interface {
	CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...client.CallOption) (*CreateClusterResponse, error)
}

type tiCPClusterService struct {
	c    client.Client
	name string
}

func NewTiCPClusterService(name string, c client.Client) TiCPClusterService {
	return &tiCPClusterService{
		c:    c,
		name: name,
	}
}

func (c *tiCPClusterService) CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...client.CallOption) (*CreateClusterResponse, error) {
	req := c.c.NewRequest(c.name, "TiCPClusterService.CreateCluster", in)
	out := new(CreateClusterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TiCPClusterService service

type TiCPClusterServiceHandler interface {
	CreateCluster(context.Context, *CreateClusterRequest, *CreateClusterResponse) error
}

func RegisterTiCPClusterServiceHandler(s server.Server, hdlr TiCPClusterServiceHandler, opts ...server.HandlerOption) error {
	type tiCPClusterService interface {
		CreateCluster(ctx context.Context, in *CreateClusterRequest, out *CreateClusterResponse) error
	}
	type TiCPClusterService struct {
		tiCPClusterService
	}
	h := &tiCPClusterServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&TiCPClusterService{h}, opts...))
}

type tiCPClusterServiceHandler struct {
	TiCPClusterServiceHandler
}

func (h *tiCPClusterServiceHandler) CreateCluster(ctx context.Context, in *CreateClusterRequest, out *CreateClusterResponse) error {
	return h.TiCPClusterServiceHandler.CreateCluster(ctx, in, out)
}
