// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: cluster.proto

package cluster

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ClusterService service

func NewClusterServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ClusterService service

type ClusterService interface {
	CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...client.CallOption) (*CreateClusterResponse, error)
	QueryCluster(ctx context.Context, in *QueryClusterRequest, opts ...client.CallOption) (*QueryClusterResponse, error)
}

type clusterService struct {
	c    client.Client
	name string
}

func NewClusterService(name string, c client.Client) ClusterService {
	return &clusterService{
		c:    c,
		name: name,
	}
}

func (c *clusterService) CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...client.CallOption) (*CreateClusterResponse, error) {
	req := c.c.NewRequest(c.name, "ClusterService.CreateCluster", in)
	out := new(CreateClusterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterService) QueryCluster(ctx context.Context, in *QueryClusterRequest, opts ...client.CallOption) (*QueryClusterResponse, error) {
	req := c.c.NewRequest(c.name, "ClusterService.QueryCluster", in)
	out := new(QueryClusterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ClusterService service

type ClusterServiceHandler interface {
	CreateCluster(context.Context, *CreateClusterRequest, *CreateClusterResponse) error
	QueryCluster(context.Context, *QueryClusterRequest, *QueryClusterResponse) error
}

func RegisterClusterServiceHandler(s server.Server, hdlr ClusterServiceHandler, opts ...server.HandlerOption) error {
	type clusterService interface {
		CreateCluster(ctx context.Context, in *CreateClusterRequest, out *CreateClusterResponse) error
		QueryCluster(ctx context.Context, in *QueryClusterRequest, out *QueryClusterResponse) error
	}
	type ClusterService struct {
		clusterService
	}
	h := &clusterServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ClusterService{h}, opts...))
}

type clusterServiceHandler struct {
	ClusterServiceHandler
}

func (h *clusterServiceHandler) CreateCluster(ctx context.Context, in *CreateClusterRequest, out *CreateClusterResponse) error {
	return h.ClusterServiceHandler.CreateCluster(ctx, in, out)
}

func (h *clusterServiceHandler) QueryCluster(ctx context.Context, in *QueryClusterRequest, out *QueryClusterResponse) error {
	return h.ClusterServiceHandler.QueryCluster(ctx, in, out)
}
