# options for analysis running
run:
  timeout: 10m

linters:
  enable:
    #- misspell
    - ineffassign
    - typecheck
    - varcheck
    - unused
    - structcheck
    - deadcode
    - gosimple
    #- goimports
    - staticcheck
    #- stylecheck
    #- gosec
  disable:
    - errcheck

linters-settings:

  staticcheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.16"
    # https://staticcheck.io/docs/options#checks
    checks: [ "all" ]

  stylecheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.16"
    # https://staticcheck.io/docs/options#checks
    checks: [ "all"]

