// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: manager.proto

package manager

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for TiCPManagerService service

func NewTiCPManagerServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for TiCPManagerService service

type TiCPManagerService interface {
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...client.CallOption) (*LogoutResponse, error)
	VerifyIdentity(ctx context.Context, in *VerifyIdentityRequest, opts ...client.CallOption) (*VerifyIdentityResponse, error)
}

type tiCPManagerService struct {
	c    client.Client
	name string
}

func NewTiCPManagerService(name string, c client.Client) TiCPManagerService {
	return &tiCPManagerService{
		c:    c,
		name: name,
	}
}

func (c *tiCPManagerService) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.name, "TiCPManagerService.Login", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tiCPManagerService) Logout(ctx context.Context, in *LogoutRequest, opts ...client.CallOption) (*LogoutResponse, error) {
	req := c.c.NewRequest(c.name, "TiCPManagerService.Logout", in)
	out := new(LogoutResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tiCPManagerService) VerifyIdentity(ctx context.Context, in *VerifyIdentityRequest, opts ...client.CallOption) (*VerifyIdentityResponse, error) {
	req := c.c.NewRequest(c.name, "TiCPManagerService.VerifyIdentity", in)
	out := new(VerifyIdentityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TiCPManagerService service

type TiCPManagerServiceHandler interface {
	Login(context.Context, *LoginRequest, *LoginResponse) error
	Logout(context.Context, *LogoutRequest, *LogoutResponse) error
	VerifyIdentity(context.Context, *VerifyIdentityRequest, *VerifyIdentityResponse) error
}

func RegisterTiCPManagerServiceHandler(s server.Server, hdlr TiCPManagerServiceHandler, opts ...server.HandlerOption) error {
	type tiCPManagerService interface {
		Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error
		Logout(ctx context.Context, in *LogoutRequest, out *LogoutResponse) error
		VerifyIdentity(ctx context.Context, in *VerifyIdentityRequest, out *VerifyIdentityResponse) error
	}
	type TiCPManagerService struct {
		tiCPManagerService
	}
	h := &tiCPManagerServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&TiCPManagerService{h}, opts...))
}

type tiCPManagerServiceHandler struct {
	TiCPManagerServiceHandler
}

func (h *tiCPManagerServiceHandler) Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error {
	return h.TiCPManagerServiceHandler.Login(ctx, in, out)
}

func (h *tiCPManagerServiceHandler) Logout(ctx context.Context, in *LogoutRequest, out *LogoutResponse) error {
	return h.TiCPManagerServiceHandler.Logout(ctx, in, out)
}

func (h *tiCPManagerServiceHandler) VerifyIdentity(ctx context.Context, in *VerifyIdentityRequest, out *VerifyIdentityResponse) error {
	return h.TiCPManagerServiceHandler.VerifyIdentity(ctx, in, out)
}
