// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: mng_host.proto

package manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ResponseStatus) Reset() {
	*x = ResponseStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mng_host_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStatus) ProtoMessage() {}

func (x *ResponseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_mng_host_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStatus.ProtoReflect.Descriptor instead.
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return file_mng_host_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseStatus) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Disk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiskId   string `protobuf:"bytes,1,opt,name=diskId,proto3" json:"diskId,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`          // [sda/sdb/nvmep0...]
	Capacity int32  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"` // Disk size, Unit: GB
	Path     string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`          // Disk mount path: [/data1]
	Status   int32  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Disk) Reset() {
	*x = Disk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mng_host_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_mng_host_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_mng_host_proto_rawDescGZIP(), []int{1}
}

func (x *Disk) GetDiskId() string {
	if x != nil {
		return x.DiskId
	}
	return ""
}

func (x *Disk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Disk) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Disk) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Disk) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type HostInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId   string  `protobuf:"bytes,1,opt,name=hostId,proto3" json:"hostId,omitempty"`
	HostName string  `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
	Dc       string  `protobuf:"bytes,3,opt,name=dc,proto3" json:"dc,omitempty"`
	Az       string  `protobuf:"bytes,4,opt,name=az,proto3" json:"az,omitempty"`
	Rack     string  `protobuf:"bytes,5,opt,name=rack,proto3" json:"rack,omitempty"`
	Ip       string  `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	Status   int32   `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Os       string  `protobuf:"bytes,8,opt,name=os,proto3" json:"os,omitempty"` // Host os
	Kernel   string  `protobuf:"bytes,9,opt,name=kernel,proto3" json:"kernel,omitempty"`
	CpuCores int32   `protobuf:"varint,10,opt,name=cpuCores,proto3" json:"cpuCores,omitempty"`
	Memory   int32   `protobuf:"varint,11,opt,name=memory,proto3" json:"memory,omitempty"`  // Host memory size, Unit:GB
	Nic      string  `protobuf:"bytes,12,opt,name=nic,proto3" json:"nic,omitempty"`         // Host network type: 1GE or 10GE
	Purpose  string  `protobuf:"bytes,13,opt,name=purpose,proto3" json:"purpose,omitempty"` // What Purpose is the host used for? [compute/storage or both]
	Disks    []*Disk `protobuf:"bytes,14,rep,name=disks,proto3" json:"disks,omitempty"`
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mng_host_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mng_host_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_mng_host_proto_rawDescGZIP(), []int{2}
}

func (x *HostInfo) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HostInfo) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *HostInfo) GetDc() string {
	if x != nil {
		return x.Dc
	}
	return ""
}

func (x *HostInfo) GetAz() string {
	if x != nil {
		return x.Az
	}
	return ""
}

func (x *HostInfo) GetRack() string {
	if x != nil {
		return x.Rack
	}
	return ""
}

func (x *HostInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HostInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HostInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HostInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *HostInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *HostInfo) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *HostInfo) GetNic() string {
	if x != nil {
		return x.Nic
	}
	return ""
}

func (x *HostInfo) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *HostInfo) GetDisks() []*Disk {
	if x != nil {
		return x.Disks
	}
	return nil
}

type AllocHost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostName string `protobuf:"bytes,1,opt,name=hostName,proto3" json:"hostName,omitempty"`
	Ip       string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Disk     *Disk  `protobuf:"bytes,3,opt,name=disk,proto3" json:"disk,omitempty"`
}

func (x *AllocHost) Reset() {
	*x = AllocHost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mng_host_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocHost) ProtoMessage() {}

func (x *AllocHost) ProtoReflect() protoreflect.Message {
	mi := &file_mng_host_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocHost.ProtoReflect.Descriptor instead.
func (*AllocHost) Descriptor() ([]byte, []int) {
	return file_mng_host_proto_rawDescGZIP(), []int{3}
}

func (x *AllocHost) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *AllocHost) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AllocHost) GetDisk() *Disk {
	if x != nil {
		return x.Disk
	}
	return nil
}

type ImportHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host *HostInfo `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *ImportHostRequest) Reset() {
	*x = ImportHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mng_host_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportHostRequest) ProtoMessage() {}

func (x *ImportHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mng_host_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportHostRequest.ProtoReflect.Descriptor instead.
func (*ImportHostRequest) Descriptor() ([]byte, []int) {
	return file_mng_host_proto_rawDescGZIP(), []int{4}
}

func (x *ImportHostRequest) GetHost() *HostInfo {
	if x != nil {
		return x.Host
	}
	return nil
}

type ImportHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rs     *ResponseStatus `protobuf:"bytes,1,opt,name=rs,proto3" json:"rs,omitempty"`
	HostId string          `protobuf:"bytes,2,opt,name=HostId,proto3" json:"HostId,omitempty"`
}

func (x *ImportHostResponse) Reset() {
	*x = ImportHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mng_host_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportHostResponse) ProtoMessage() {}

func (x *ImportHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mng_host_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportHostResponse.ProtoReflect.Descriptor instead.
func (*ImportHostResponse) Descriptor() ([]byte, []int) {
	return file_mng_host_proto_rawDescGZIP(), []int{5}
}

func (x *ImportHostResponse) GetRs() *ResponseStatus {
	if x != nil {
		return x.Rs
	}
	return nil
}

func (x *ImportHostResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type ImportHostsInBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hosts []*HostInfo `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
}

func (x *ImportHostsInBatchRequest) Reset() {
	*x = ImportHostsInBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mng_host_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportHostsInBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportHostsInBatchRequest) ProtoMessage() {}

func (x *ImportHostsInBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mng_host_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportHostsInBatchRequest.ProtoReflect.Descriptor instead.
func (*ImportHostsInBatchRequest) Descriptor() ([]byte, []int) {
	return file_mng_host_proto_rawDescGZIP(), []int{6}
}

func (x *ImportHostsInBatchRequest) GetHosts() []*HostInfo {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type ImportHostsInBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rs      *ResponseStatus `protobuf:"bytes,1,opt,name=rs,proto3" json:"rs,omitempty"`
	HostIds []string        `protobuf:"bytes,2,rep,name=HostIds,proto3" json:"HostIds,omitempty"`
}

func (x *ImportHostsInBatchResponse) Reset() {
	*x = ImportHostsInBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mng_host_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportHostsInBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportHostsInBatchResponse) ProtoMessage() {}

func (x *ImportHostsInBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mng_host_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportHostsInBatchResponse.ProtoReflect.Descriptor instead.
func (*ImportHostsInBatchResponse) Descriptor() ([]byte, []int) {
	return file_mng_host_proto_rawDescGZIP(), []int{7}
}

func (x *ImportHostsInBatchResponse) GetRs() *ResponseStatus {
	if x != nil {
		return x.Rs
	}
	return nil
}

func (x *ImportHostsInBatchResponse) GetHostIds() []string {
	if x != nil {
		return x.HostIds
	}
	return nil
}

type RemoveHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId string `protobuf:"bytes,1,opt,name=hostId,proto3" json:"hostId,omitempty"`
}

func (x *RemoveHostRequest) Reset() {
	*x = RemoveHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mng_host_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveHostRequest) ProtoMessage() {}

func (x *RemoveHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mng_host_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveHostRequest.ProtoReflect.Descriptor instead.
func (*RemoveHostRequest) Descriptor() ([]byte, []int) {
	return file_mng_host_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveHostRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type RemoveHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rs *ResponseStatus `protobuf:"bytes,1,opt,name=rs,proto3" json:"rs,omitempty"`
}

func (x *RemoveHostResponse) Reset() {
	*x = RemoveHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mng_host_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveHostResponse) ProtoMessage() {}

func (x *RemoveHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mng_host_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveHostResponse.ProtoReflect.Descriptor instead.
func (*RemoveHostResponse) Descriptor() ([]byte, []int) {
	return file_mng_host_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveHostResponse) GetRs() *ResponseStatus {
	if x != nil {
		return x.Rs
	}
	return nil
}

type RemoveHostsInBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostIds []string `protobuf:"bytes,1,rep,name=hostIds,proto3" json:"hostIds,omitempty"`
}

func (x *RemoveHostsInBatchRequest) Reset() {
	*x = RemoveHostsInBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mng_host_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveHostsInBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveHostsInBatchRequest) ProtoMessage() {}

func (x *RemoveHostsInBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mng_host_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveHostsInBatchRequest.ProtoReflect.Descriptor instead.
func (*RemoveHostsInBatchRequest) Descriptor() ([]byte, []int) {
	return file_mng_host_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveHostsInBatchRequest) GetHostIds() []string {
	if x != nil {
		return x.HostIds
	}
	return nil
}

type RemoveHostsInBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rs *ResponseStatus `protobuf:"bytes,1,opt,name=rs,proto3" json:"rs,omitempty"`
}

func (x *RemoveHostsInBatchResponse) Reset() {
	*x = RemoveHostsInBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mng_host_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveHostsInBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveHostsInBatchResponse) ProtoMessage() {}

func (x *RemoveHostsInBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mng_host_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveHostsInBatchResponse.ProtoReflect.Descriptor instead.
func (*RemoveHostsInBatchResponse) Descriptor() ([]byte, []int) {
	return file_mng_host_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveHostsInBatchResponse) GetRs() *ResponseStatus {
	if x != nil {
		return x.Rs
	}
	return nil
}

type ListHostsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Purpose string `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
}

func (x *ListHostsRequest) Reset() {
	*x = ListHostsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mng_host_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsRequest) ProtoMessage() {}

func (x *ListHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mng_host_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsRequest.ProtoReflect.Descriptor instead.
func (*ListHostsRequest) Descriptor() ([]byte, []int) {
	return file_mng_host_proto_rawDescGZIP(), []int{12}
}

func (x *ListHostsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListHostsRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

type ListHostsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rs       *ResponseStatus `protobuf:"bytes,1,opt,name=rs,proto3" json:"rs,omitempty"`
	HostList []*HostInfo     `protobuf:"bytes,2,rep,name=hostList,proto3" json:"hostList,omitempty"`
}

func (x *ListHostsResponse) Reset() {
	*x = ListHostsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mng_host_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsResponse) ProtoMessage() {}

func (x *ListHostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mng_host_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsResponse.ProtoReflect.Descriptor instead.
func (*ListHostsResponse) Descriptor() ([]byte, []int) {
	return file_mng_host_proto_rawDescGZIP(), []int{13}
}

func (x *ListHostsResponse) GetRs() *ResponseStatus {
	if x != nil {
		return x.Rs
	}
	return nil
}

func (x *ListHostsResponse) GetHostList() []*HostInfo {
	if x != nil {
		return x.HostList
	}
	return nil
}

type CheckDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId string `protobuf:"bytes,1,opt,name=hostId,proto3" json:"hostId,omitempty"`
}

func (x *CheckDetailsRequest) Reset() {
	*x = CheckDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mng_host_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDetailsRequest) ProtoMessage() {}

func (x *CheckDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mng_host_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDetailsRequest.ProtoReflect.Descriptor instead.
func (*CheckDetailsRequest) Descriptor() ([]byte, []int) {
	return file_mng_host_proto_rawDescGZIP(), []int{14}
}

func (x *CheckDetailsRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type CheckDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rs      *ResponseStatus `protobuf:"bytes,1,opt,name=rs,proto3" json:"rs,omitempty"`
	Details *HostInfo       `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *CheckDetailsResponse) Reset() {
	*x = CheckDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mng_host_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDetailsResponse) ProtoMessage() {}

func (x *CheckDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mng_host_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDetailsResponse.ProtoReflect.Descriptor instead.
func (*CheckDetailsResponse) Descriptor() ([]byte, []int) {
	return file_mng_host_proto_rawDescGZIP(), []int{15}
}

func (x *CheckDetailsResponse) GetRs() *ResponseStatus {
	if x != nil {
		return x.Rs
	}
	return nil
}

func (x *CheckDetailsResponse) GetDetails() *HostInfo {
	if x != nil {
		return x.Details
	}
	return nil
}

type AllocHostsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PdCount   int32 `protobuf:"varint,1,opt,name=pdCount,proto3" json:"pdCount,omitempty"`
	TidbCount int32 `protobuf:"varint,2,opt,name=tidbCount,proto3" json:"tidbCount,omitempty"`
	TikvCount int32 `protobuf:"varint,3,opt,name=tikvCount,proto3" json:"tikvCount,omitempty"`
}

func (x *AllocHostsRequest) Reset() {
	*x = AllocHostsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mng_host_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocHostsRequest) ProtoMessage() {}

func (x *AllocHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mng_host_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocHostsRequest.ProtoReflect.Descriptor instead.
func (*AllocHostsRequest) Descriptor() ([]byte, []int) {
	return file_mng_host_proto_rawDescGZIP(), []int{16}
}

func (x *AllocHostsRequest) GetPdCount() int32 {
	if x != nil {
		return x.PdCount
	}
	return 0
}

func (x *AllocHostsRequest) GetTidbCount() int32 {
	if x != nil {
		return x.TidbCount
	}
	return 0
}

func (x *AllocHostsRequest) GetTikvCount() int32 {
	if x != nil {
		return x.TikvCount
	}
	return 0
}

type AllocHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rs    *ResponseStatus `protobuf:"bytes,1,opt,name=rs,proto3" json:"rs,omitempty"`
	Hosts []*AllocHost    `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts,omitempty"`
}

func (x *AllocHostResponse) Reset() {
	*x = AllocHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mng_host_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocHostResponse) ProtoMessage() {}

func (x *AllocHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mng_host_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocHostResponse.ProtoReflect.Descriptor instead.
func (*AllocHostResponse) Descriptor() ([]byte, []int) {
	return file_mng_host_proto_rawDescGZIP(), []int{17}
}

func (x *AllocHostResponse) GetRs() *ResponseStatus {
	if x != nil {
		return x.Rs
	}
	return nil
}

func (x *AllocHostResponse) GetHosts() []*AllocHost {
	if x != nil {
		return x.Hosts
	}
	return nil
}

var File_mng_host_proto protoreflect.FileDescriptor

var file_mng_host_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x6e, 0x67, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x3e, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x7a, 0x0a, 0x04, 0x44, 0x69, 0x73, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x73, 0x6b,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x69, 0x73, 0x6b, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xbf, 0x02, 0x0a,
	0x08, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x73,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x64, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x63, 0x12, 0x0e, 0x0a,
	0x02, 0x61, 0x7a, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x61, 0x7a, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x61, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x61, 0x63,
	0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6b, 0x65, 0x72,
	0x6e, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x65, 0x72, 0x6e, 0x65,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x70, 0x75, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x70, 0x75, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x63, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6e, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x75, 0x72, 0x70, 0x6f,
	0x73, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73,
	0x65, 0x12, 0x1b, 0x0a, 0x05, 0x64, 0x69, 0x73, 0x6b, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x52, 0x05, 0x64, 0x69, 0x73, 0x6b, 0x73, 0x22, 0x52,
	0x0a, 0x09, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x68,
	0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68,
	0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x69, 0x73, 0x6b, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x52, 0x04, 0x64, 0x69,
	0x73, 0x6b, 0x22, 0x32, 0x0a, 0x11, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x48, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x22, 0x4d, 0x0a, 0x12, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x02,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x02, 0x72, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x48,
	0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x19, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x48,
	0x6f, 0x73, 0x74, 0x73, 0x49, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x68, 0x6f,
	0x73, 0x74, 0x73, 0x22, 0x57, 0x0a, 0x1a, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x48, 0x6f, 0x73,
	0x74, 0x73, 0x49, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1f, 0x0a, 0x02, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x02,
	0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x73, 0x22, 0x2b, 0x0a, 0x11,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x12, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x02, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x02, 0x72, 0x73,
	0x22, 0x35, 0x0a, 0x19, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x49,
	0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x73, 0x22, 0x3d, 0x0a, 0x1a, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x49, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x02, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x02, 0x72, 0x73, 0x22, 0x44, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f,
	0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x22, 0x5b, 0x0a, 0x11,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1f, 0x0a, 0x02, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x02,
	0x72, 0x73, 0x12, 0x25, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x08, 0x68, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2d, 0x0a, 0x13, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x5c, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x02, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x02, 0x72,
	0x73, 0x12, 0x23, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x69, 0x0a, 0x11, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x48,
	0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x64,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x64, 0x62, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x69, 0x64, 0x62, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6b, 0x76, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x69, 0x6b, 0x76, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x56, 0x0a, 0x11, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x02, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x02, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x48, 0x6f,
	0x73, 0x74, 0x52, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mng_host_proto_rawDescOnce sync.Once
	file_mng_host_proto_rawDescData = file_mng_host_proto_rawDesc
)

func file_mng_host_proto_rawDescGZIP() []byte {
	file_mng_host_proto_rawDescOnce.Do(func() {
		file_mng_host_proto_rawDescData = protoimpl.X.CompressGZIP(file_mng_host_proto_rawDescData)
	})
	return file_mng_host_proto_rawDescData
}

var file_mng_host_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_mng_host_proto_goTypes = []interface{}{
	(*ResponseStatus)(nil),             // 0: ResponseStatus
	(*Disk)(nil),                       // 1: Disk
	(*HostInfo)(nil),                   // 2: HostInfo
	(*AllocHost)(nil),                  // 3: AllocHost
	(*ImportHostRequest)(nil),          // 4: ImportHostRequest
	(*ImportHostResponse)(nil),         // 5: ImportHostResponse
	(*ImportHostsInBatchRequest)(nil),  // 6: ImportHostsInBatchRequest
	(*ImportHostsInBatchResponse)(nil), // 7: ImportHostsInBatchResponse
	(*RemoveHostRequest)(nil),          // 8: RemoveHostRequest
	(*RemoveHostResponse)(nil),         // 9: RemoveHostResponse
	(*RemoveHostsInBatchRequest)(nil),  // 10: RemoveHostsInBatchRequest
	(*RemoveHostsInBatchResponse)(nil), // 11: RemoveHostsInBatchResponse
	(*ListHostsRequest)(nil),           // 12: ListHostsRequest
	(*ListHostsResponse)(nil),          // 13: ListHostsResponse
	(*CheckDetailsRequest)(nil),        // 14: CheckDetailsRequest
	(*CheckDetailsResponse)(nil),       // 15: CheckDetailsResponse
	(*AllocHostsRequest)(nil),          // 16: AllocHostsRequest
	(*AllocHostResponse)(nil),          // 17: AllocHostResponse
}
var file_mng_host_proto_depIdxs = []int32{
	1,  // 0: HostInfo.disks:type_name -> Disk
	1,  // 1: AllocHost.disk:type_name -> Disk
	2,  // 2: ImportHostRequest.host:type_name -> HostInfo
	0,  // 3: ImportHostResponse.rs:type_name -> ResponseStatus
	2,  // 4: ImportHostsInBatchRequest.hosts:type_name -> HostInfo
	0,  // 5: ImportHostsInBatchResponse.rs:type_name -> ResponseStatus
	0,  // 6: RemoveHostResponse.rs:type_name -> ResponseStatus
	0,  // 7: RemoveHostsInBatchResponse.rs:type_name -> ResponseStatus
	0,  // 8: ListHostsResponse.rs:type_name -> ResponseStatus
	2,  // 9: ListHostsResponse.hostList:type_name -> HostInfo
	0,  // 10: CheckDetailsResponse.rs:type_name -> ResponseStatus
	2,  // 11: CheckDetailsResponse.details:type_name -> HostInfo
	0,  // 12: AllocHostResponse.rs:type_name -> ResponseStatus
	3,  // 13: AllocHostResponse.hosts:type_name -> AllocHost
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_mng_host_proto_init() }
func file_mng_host_proto_init() {
	if File_mng_host_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mng_host_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mng_host_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Disk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mng_host_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mng_host_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocHost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mng_host_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mng_host_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mng_host_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportHostsInBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mng_host_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportHostsInBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mng_host_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mng_host_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mng_host_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveHostsInBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mng_host_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveHostsInBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mng_host_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHostsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mng_host_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHostsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mng_host_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mng_host_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mng_host_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocHostsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mng_host_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mng_host_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mng_host_proto_goTypes,
		DependencyIndexes: file_mng_host_proto_depIdxs,
		MessageInfos:      file_mng_host_proto_msgTypes,
	}.Build()
	File_mng_host_proto = out.File
	file_mng_host_proto_rawDesc = nil
	file_mng_host_proto_goTypes = nil
	file_mng_host_proto_depIdxs = nil
}
