/******************************************************************************
 * Copyright (c)  2021 PingCAP, Inc.                                          *
 * Licensed under the Apache License, Version 2.0 (the "License");            *
 * you may not use this file except in compliance with the License.           *
 * You may obtain a copy of the License at                                    *
 *                                                                            *
 * http://www.apache.org/licenses/LICENSE-2.0                                 *
 *                                                                            *
 * Unless required by applicable law or agreed to in writing, software        *
 * distributed under the License is distributed on an "AS IS" BASIS,          *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   *
 * See the License for the specific language governing permissions and        *
 * limitations under the License.                                             *
 *                                                                            *
 ******************************************************************************/

package errors

type EM_ERROR_CODE int32

const (
	TIEM_SUCCESS EM_ERROR_CODE = 0

	TIEM_UNRECOGNIZED_ERROR EM_ERROR_CODE = 10000
	TIEM_PARAMETER_INVALID  EM_ERROR_CODE = 10001
	TIEM_SQL_ERROR          EM_ERROR_CODE = 10002
	TIEM_CLUSTER_NOT_FOUND  EM_ERROR_CODE = 10003
	TIEM_MARSHAL_ERROR      EM_ERROR_CODE = 10004
	TIEM_UNMARSHAL_ERROR    EM_ERROR_CODE = 10005

	// cluster
	TIEM_DUPLICATED_NAME             EM_ERROR_CODE = 20101
	TIEM_INVALID_TOPOLOGY            EM_ERROR_CODE = 20102
	TIEM_UNSUPPPORT_PRODUCT          EM_ERROR_CODE = 20103
	TIEM_CLUSTER_RESOURCE_NOT_ENOUGH EM_ERROR_CODE = 20104

	TIEM_TAKEOVER_SSH_CONNECT_ERROR     EM_ERROR_CODE = 20201
	TIEM_TAKEOVER_SFTP_ERROR            EM_ERROR_CODE = 20110
	TIEM_CLUSTER_GET_CLUSTER_PORT_ERROR EM_ERROR_CODE = 20113
	TIEM_CLUSTER_MAINTENANCE_CONFLICT   EM_ERROR_CODE = 20114

	// backup && restore
	TIEM_BACKUP_SYSTEM_CONFIG_NOT_FOUND EM_ERROR_CODE = 20600
	TIEM_BACKUP_SYSTEM_CONFIG_INVAILD   EM_ERROR_CODE = 20601
	TIEM_BACKUP_RECORD_CREATE_FAILED    EM_ERROR_CODE = 20602
	TIEM_BACKUP_RECORD_DELETE_FAILED    EM_ERROR_CODE = 20603
	TIEM_BACKUP_RECORD_QUERY_FAILED     EM_ERROR_CODE = 20604
	TIEM_BACKUP_STRATEGY_SAVE_FAILED    EM_ERROR_CODE = 20605
	TIEM_BACKUP_STRATEGY_QUERY_FAILED   EM_ERROR_CODE = 20606
	TIEM_BACKUP_STRATEGY_DELETE_FAILED  EM_ERROR_CODE = 20607
	TIEM_BACKUP_FILE_DELETE_FAILED      EM_ERROR_CODE = 20608
	TIEM_BACKUP_PATH_CREATE_FAILED      EM_ERROR_CODE = 20609

	// workflow
	TIEM_WORKFLOW_CREATE_FAILED    EM_ERROR_CODE = 40100
	TIEM_WORKFLOW_QUERY_FAILED     EM_ERROR_CODE = 40101
	TIEM_WORKFLOW_DETAIL_FAILED    EM_ERROR_CODE = 40102
	TIEM_WORKFLOW_START_FAILED     EM_ERROR_CODE = 40103
	TIEM_WORKFLOW_DEFINE_NOT_FOUND EM_ERROR_CODE = 40104

	// import && export
	TIEM_TRANSPORT_SYSTEM_CONFIG_NOT_FOUND EM_ERROR_CODE = 60100
	TIEM_TRANSPORT_SYSTEM_CONFIG_INVALID   EM_ERROR_CODE = 60101
	TIEM_TRANSPORT_RECORD_NOT_FOUND        EM_ERROR_CODE = 60102
	TIEM_TRANSPORT_RECORD_CREATE_FAILED    EM_ERROR_CODE = 60103
	TIEM_TRANSPORT_RECORD_DELETE_FAILED    EM_ERROR_CODE = 60104
	TIEM_TRANSPORT_RECORD_QUERY_FAILED     EM_ERROR_CODE = 60105
	TIEM_TRANSPORT_FILE_DELETE_FAILED      EM_ERROR_CODE = 60106
	TIEM_TRANSPORT_PATH_CREATE_FAILED      EM_ERROR_CODE = 60107
	TIEM_TRANSPORT_FILE_SIZE_INVALID       EM_ERROR_CODE = 60108
	TIEM_TRANSPORT_FILE_UPLOAD_FAILED      EM_ERROR_CODE = 60109
	TIEM_TRANSPORT_FILE_DOWNLOAD_FAILED    EM_ERROR_CODE = 60110
	TIEM_TRANSPORT_FILE_TRANSFER_LIMITED   EM_ERROR_CODE = 60111

	// dashboard && monitor
	TIEM_DASHBOARD_NOT_FOUND EM_ERROR_CODE = 80100

	TIEM_ACCOUNT_NOT_FOUND       EM_ERROR_CODE = 100
	TIEM_TENANT_NOT_FOUND        EM_ERROR_CODE = 200
	TIEM_QUERY_PERMISSION_FAILED EM_ERROR_CODE = 300
	TIEM_ADD_TOKEN_FAILED        EM_ERROR_CODE = 400
	TIEM_TOKEN_NOT_FOUND         EM_ERROR_CODE = 401

	TIEM_RESOURCE_HOST_NOT_FOUND            EM_ERROR_CODE = 30101
	TIEM_RESOURCE_NO_ENOUGH_HOST            EM_ERROR_CODE = 30102
	TIEM_RESOURCE_NO_ENOUGH_DISK            EM_ERROR_CODE = 30103
	TIEM_RESOURCE_NO_ENOUGH_PORT            EM_ERROR_CODE = 30104
	TIEM_UPDATE_HOST_STATUS_FAIL            EM_ERROR_CODE = 30105
	TIEM_RESERVE_HOST_FAIL                  EM_ERROR_CODE = 30106
	TIEM_RESOURCE_NO_STOCK                  EM_ERROR_CODE = 30107
	TIEM_RESOURCE_TRAIT_NOT_FOUND           EM_ERROR_CODE = 30108
	TIEM_RESOURCE_INVALID_LOCATION          EM_ERROR_CODE = 30109
	TIEM_RESOURCE_INVALID_ARCH              EM_ERROR_CODE = 30110
	TIEM_RESOURCE_ADD_TABLE_ERROR           EM_ERROR_CODE = 30111
	TIEM_RESOURCE_INIT_LABELS_ERROR         EM_ERROR_CODE = 30112
	TIEM_RESOURCE_CREATE_HOST_ERROR         EM_ERROR_CODE = 30113
	TIEM_RESOURCE_DELETE_HOST_ERROR         EM_ERROR_CODE = 30114
	TIEM_RESOURCE_INVALID_PRODUCT_NAME      EM_ERROR_CODE = 30115
	TIEM_RESOURCE_INVALID_PURPOSE           EM_ERROR_CODE = 30116
	TIEM_RESOURCE_INVALID_DISKTYPE          EM_ERROR_CODE = 30117
	TIEM_RESOURCE_HOST_ALREADY_EXIST        EM_ERROR_CODE = 30118
	TIEM_RESOURCE_HOST_STILL_INUSED         EM_ERROR_CODE = 30119
	TIEM_RESOURCE_CREATE_DISK_ERROR         EM_ERROR_CODE = 30120
	TIEM_RESOURCE_TEMPLATE_FILE_NOT_FOUND   EM_ERROR_CODE = 30121
	TIEM_RESOURCE_PARSE_TEMPLATE_FILE_ERROR EM_ERROR_CODE = 30122
	TIEM_RESOURCE_DECRYPT_PASSWD_ERROR      EM_ERROR_CODE = 30123
	TIEM_RESOURCE_ALLOCATE_ERROR            EM_ERROR_CODE = 30124
	TIEM_RESOURCE_RECYCLE_ERROR             EM_ERROR_CODE = 30125

	TIEM_MONITOR_NOT_FOUND EM_ERROR_CODE = 614

	TIEM_DEFAULT_PARAM_GROUP_NOT_DEL EM_ERROR_CODE = 20500

	TIEM_CHANGE_FEED_NOT_FOUND EM_ERROR_CODE = 701

	TIEM_CHANGE_FEED_DUPLICATE_ID           EM_ERROR_CODE = 702
	TIEM_CHANGE_FEED_STATUS_CONFLICT        EM_ERROR_CODE = 703
	TIEM_CHANGE_FEED_LOCK_EXPIRED           EM_ERROR_CODE = 704
	TIEM_CHANGE_FEED_UNSUPPORTED_DOWNSTREAM EM_ERROR_CODE = 705

	TIEM_INSTANCE_NOT_FOUND          EM_ERROR_CODE = 20801
	TIEM_DELETE_INSTANCE_ERROR       EM_ERROR_CODE = 20802
	TIEM_CHECK_PLACEMENT_RULES_ERROR EM_ERROR_CODE = 20803

	TIEM_CHECK_TIFLASH_MAX_REPLICAS_ERROR EM_ERROR_CODE = 20901
	TIEM_NOT_FOUND_TIDB_ERROR             EM_ERROR_CODE = 20902
	TIEM_CONNECT_DB_ERROR                 EM_ERROR_CODE = 20903
	TIEM_SCAN_MAX_REPLICA_COUNT_ERROR     EM_ERROR_CODE = 20904
	TIEM_WAIT_WORKFLOW_TIMEOUT_ERROR      EM_ERROR_CODE = 20905
	TIEM_WAIT_WORKFLOW_RUN_ERROR          EM_ERROR_CODE = 20906

	TIEM_CHECK_CLUSTER_VERSION_ERROR EM_ERROR_CODE = 21301

	QueryProductComponentProperty = 706 //TODO
	QueryProductsScanRowError     = 707 //TODO
	QueryZoneScanRowError         = 708 //TODO
)

type ErrorCodeExplanation struct {
	code        EM_ERROR_CODE
	explanation string
	httpCode    int
}

func (t EM_ERROR_CODE) GetHttpCode() int {
	return explanationContainer[t].httpCode
}

func (t EM_ERROR_CODE) Equal(code int32) bool {
	return code == int32(t)
}

func (t EM_ERROR_CODE) Explain() string {
	return explanationContainer[t].explanation
}

var explanationContainer = map[EM_ERROR_CODE]ErrorCodeExplanation{
	TIEM_SUCCESS: {code: TIEM_SUCCESS, explanation: "succeed", httpCode: 200},

	// system error
	TIEM_UNRECOGNIZED_ERROR: {TIEM_UNRECOGNIZED_ERROR, "unrecognized error", 500},
	TIEM_PARAMETER_INVALID:  {TIEM_PARAMETER_INVALID, "parameter is invalid", 400},
	TIEM_SQL_ERROR:          {TIEM_SQL_ERROR, "failed to execute SQL", 500},
	TIEM_CLUSTER_NOT_FOUND:  {TIEM_CLUSTER_NOT_FOUND, "cluster not found", 404},
	TIEM_MARSHAL_ERROR:      {TIEM_MARSHAL_ERROR, "marshal error", 500},
	TIEM_UNMARSHAL_ERROR:    {TIEM_UNMARSHAL_ERROR, "marshal error", 500},

	TIEM_DUPLICATED_NAME:              {TIEM_DUPLICATED_NAME, "duplicated cluster name", 400},
	TIEM_INVALID_TOPOLOGY:             {TIEM_INVALID_TOPOLOGY, "invalid cluster topology", 400},
	TIEM_UNSUPPPORT_PRODUCT:           {TIEM_UNSUPPPORT_PRODUCT, "unsupported cluster type or version", 400},
	TIEM_CLUSTER_RESOURCE_NOT_ENOUGH:  {TIEM_CLUSTER_RESOURCE_NOT_ENOUGH, "host resource is not enough", 500},
	TIEM_CLUSTER_MAINTENANCE_CONFLICT: {TIEM_CLUSTER_MAINTENANCE_CONFLICT, "maintenance status conflict", 209},

	// cluster management
	TIEM_TAKEOVER_SSH_CONNECT_ERROR: {TIEM_TAKEOVER_SSH_CONNECT_ERROR, "ssh connect failed", 500},
	TIEM_TAKEOVER_SFTP_ERROR:        {TIEM_TAKEOVER_SFTP_ERROR, "sftp failed", 500},

	// dashboard && monitor
	TIEM_DASHBOARD_NOT_FOUND: {TIEM_DASHBOARD_NOT_FOUND, "dashboard is not found", 500},

	// workflow
	TIEM_WORKFLOW_CREATE_FAILED:    {TIEM_WORKFLOW_CREATE_FAILED, "workflow create failed", 500},
	TIEM_WORKFLOW_QUERY_FAILED:     {TIEM_WORKFLOW_QUERY_FAILED, "workflow query failed", 500},
	TIEM_WORKFLOW_DETAIL_FAILED:    {TIEM_WORKFLOW_DETAIL_FAILED, "workflow detail failed", 500},
	TIEM_WORKFLOW_START_FAILED:     {TIEM_WORKFLOW_START_FAILED, "workflow start failed", 500},
	TIEM_WORKFLOW_DEFINE_NOT_FOUND: {TIEM_WORKFLOW_DEFINE_NOT_FOUND, "workflow define not found", 404},

	// import && export
	TIEM_TRANSPORT_SYSTEM_CONFIG_NOT_FOUND: {TIEM_TRANSPORT_SYSTEM_CONFIG_NOT_FOUND, "data transport system config not found", 404},
	TIEM_TRANSPORT_SYSTEM_CONFIG_INVALID:   {TIEM_TRANSPORT_SYSTEM_CONFIG_INVALID, "data transport system config invalid", 400},
	TIEM_TRANSPORT_RECORD_NOT_FOUND:        {TIEM_TRANSPORT_RECORD_NOT_FOUND, "data transport record is not found", 404},
	TIEM_TRANSPORT_RECORD_CREATE_FAILED:    {TIEM_TRANSPORT_RECORD_CREATE_FAILED, "create data transport record failed", 500},
	TIEM_TRANSPORT_RECORD_DELETE_FAILED:    {TIEM_TRANSPORT_RECORD_DELETE_FAILED, "delete data transport record failed", 500},
	TIEM_TRANSPORT_RECORD_QUERY_FAILED:     {TIEM_TRANSPORT_RECORD_QUERY_FAILED, "query data transport record failed", 500},
	TIEM_TRANSPORT_FILE_DELETE_FAILED:      {TIEM_TRANSPORT_FILE_DELETE_FAILED, "remove transport file failed", 500},
	TIEM_TRANSPORT_PATH_CREATE_FAILED:      {TIEM_TRANSPORT_PATH_CREATE_FAILED, "data transport filepath create failed", 500},
	TIEM_TRANSPORT_FILE_SIZE_INVALID:       {TIEM_TRANSPORT_FILE_SIZE_INVALID, "data transport file size invalid", 400},
	TIEM_TRANSPORT_FILE_UPLOAD_FAILED:      {TIEM_TRANSPORT_FILE_UPLOAD_FAILED, "data transport file upload failed", 500},
	TIEM_TRANSPORT_FILE_DOWNLOAD_FAILED:    {TIEM_TRANSPORT_FILE_DOWNLOAD_FAILED, "data transport file download failed", 500},
	TIEM_TRANSPORT_FILE_TRANSFER_LIMITED:   {TIEM_TRANSPORT_FILE_TRANSFER_LIMITED, "exceed limit file transfer num", 400},

	// backup && restore
	TIEM_BACKUP_SYSTEM_CONFIG_NOT_FOUND: {TIEM_BACKUP_SYSTEM_CONFIG_NOT_FOUND, "backup system config not found", 404},
	TIEM_BACKUP_SYSTEM_CONFIG_INVAILD:   {TIEM_BACKUP_SYSTEM_CONFIG_INVAILD, "backup system config invalid", 400},
	TIEM_BACKUP_RECORD_CREATE_FAILED:    {TIEM_BACKUP_RECORD_CREATE_FAILED, "create backup record failed", 500},
	TIEM_BACKUP_RECORD_DELETE_FAILED:    {TIEM_BACKUP_RECORD_DELETE_FAILED, "delete backup record failed", 500},
	TIEM_BACKUP_RECORD_QUERY_FAILED:     {TIEM_BACKUP_RECORD_QUERY_FAILED, "query backup record failed", 500},
	TIEM_BACKUP_STRATEGY_SAVE_FAILED:    {TIEM_BACKUP_STRATEGY_SAVE_FAILED, "save backup strategy failed", 500},
	TIEM_BACKUP_STRATEGY_QUERY_FAILED:   {TIEM_BACKUP_STRATEGY_QUERY_FAILED, "query backup strategy failed", 500},
	TIEM_BACKUP_STRATEGY_DELETE_FAILED:  {TIEM_BACKUP_STRATEGY_DELETE_FAILED, "delete backup strategy failed", 500},
	TIEM_BACKUP_FILE_DELETE_FAILED:      {TIEM_BACKUP_FILE_DELETE_FAILED, "remove backup file failed", 500},
	TIEM_BACKUP_PATH_CREATE_FAILED:      {TIEM_BACKUP_PATH_CREATE_FAILED, "backup filepath create failed", 500},

	// resource
	TIEM_RESOURCE_HOST_NOT_FOUND:            {TIEM_RESOURCE_HOST_NOT_FOUND, "host not found", 500},
	TIEM_UPDATE_HOST_STATUS_FAIL:            {TIEM_UPDATE_HOST_STATUS_FAIL, "update host status failed", 500},
	TIEM_RESERVE_HOST_FAIL:                  {TIEM_RESERVE_HOST_FAIL, "reserved host failed", 500},
	TIEM_RESOURCE_NO_STOCK:                  {TIEM_RESOURCE_NO_STOCK, "Insufficient resources for inventory inquiries", 400},
	TIEM_RESOURCE_TRAIT_NOT_FOUND:           {TIEM_RESOURCE_TRAIT_NOT_FOUND, "trait not found by label name", 400},
	TIEM_RESOURCE_INVALID_LOCATION:          {TIEM_RESOURCE_INVALID_LOCATION, "invalid location of host", 400},
	TIEM_RESOURCE_INVALID_ARCH:              {TIEM_RESOURCE_INVALID_ARCH, "invalid architecture of host", 400},
	TIEM_RESOURCE_ADD_TABLE_ERROR:           {TIEM_RESOURCE_ADD_TABLE_ERROR, "failed to create database for resources", 500},
	TIEM_RESOURCE_INIT_LABELS_ERROR:         {TIEM_RESOURCE_INIT_LABELS_ERROR, "failed to initiate label table ", 500},
	TIEM_RESOURCE_CREATE_HOST_ERROR:         {TIEM_RESOURCE_CREATE_HOST_ERROR, "failed to create hosts to db", 500},
	TIEM_RESOURCE_DELETE_HOST_ERROR:         {TIEM_RESOURCE_DELETE_HOST_ERROR, "failed to delete hosts", 500},
	TIEM_RESOURCE_INVALID_PRODUCT_NAME:      {TIEM_RESOURCE_INVALID_PRODUCT_NAME, "invalid product name", 400},
	TIEM_RESOURCE_INVALID_PURPOSE:           {TIEM_RESOURCE_INVALID_PURPOSE, "invalid purpose of host", 400},
	TIEM_RESOURCE_INVALID_DISKTYPE:          {TIEM_RESOURCE_INVALID_DISKTYPE, "invalid disk type of host", 400},
	TIEM_RESOURCE_HOST_ALREADY_EXIST:        {TIEM_RESOURCE_HOST_ALREADY_EXIST, "host already exists in the resource pool", 409},
	TIEM_RESOURCE_HOST_STILL_INUSED:         {TIEM_RESOURCE_HOST_STILL_INUSED, "host is still in use", 409},
	TIEM_RESOURCE_CREATE_DISK_ERROR:         {TIEM_RESOURCE_CREATE_DISK_ERROR, "ailed to update disk table", 500},
	TIEM_RESOURCE_TEMPLATE_FILE_NOT_FOUND:   {TIEM_RESOURCE_TEMPLATE_FILE_NOT_FOUND, "template file is not found", 500},
	TIEM_RESOURCE_PARSE_TEMPLATE_FILE_ERROR: {TIEM_RESOURCE_PARSE_TEMPLATE_FILE_ERROR, "parse template file failed", 400},

	// tenant
	TIEM_ACCOUNT_NOT_FOUND:       {TIEM_ACCOUNT_NOT_FOUND, "account not found", 500},
	TIEM_TENANT_NOT_FOUND:        {TIEM_TENANT_NOT_FOUND, "tenant not found", 500},
	TIEM_QUERY_PERMISSION_FAILED: {TIEM_QUERY_PERMISSION_FAILED, "query permission failed", 500},
	TIEM_ADD_TOKEN_FAILED:        {TIEM_ADD_TOKEN_FAILED, "add token failed", 500},
	TIEM_TOKEN_NOT_FOUND:         {TIEM_TOKEN_NOT_FOUND, "token not found", 500},

	// param group & cluster param
	TIEM_DEFAULT_PARAM_GROUP_NOT_DEL: {TIEM_DEFAULT_PARAM_GROUP_NOT_DEL, "The default param group cannot be deleted", 500},

	// change feed
	TIEM_CHANGE_FEED_NOT_FOUND:              {TIEM_CHANGE_FEED_NOT_FOUND, "change feed task not found", 404},
	TIEM_CHANGE_FEED_DUPLICATE_ID:           {TIEM_CHANGE_FEED_DUPLICATE_ID, "duplicate id", 500},
	TIEM_CHANGE_FEED_STATUS_CONFLICT:        {TIEM_CHANGE_FEED_STATUS_CONFLICT, "task status conflict", 409},
	TIEM_CHANGE_FEED_LOCK_EXPIRED:           {TIEM_CHANGE_FEED_LOCK_EXPIRED, "task status lock expired", 409},
	TIEM_CHANGE_FEED_UNSUPPORTED_DOWNSTREAM: {TIEM_CHANGE_FEED_UNSUPPORTED_DOWNSTREAM, "task downstream type not supported", 500},
}
