// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: tcp.proto

package tcp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Tcp service

func NewTcpEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Tcp service

type TcpService interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error)
}

type tcpService struct {
	c    client.Client
	name string
}

func NewTcpService(name string, c client.Client) TcpService {
	return &tcpService{
		c:    c,
		name: name,
	}
}

func (c *tcpService) Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error) {
	req := c.c.NewRequest(c.name, "Tcp.Hello", in)
	out := new(HelloResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tcp service

type TcpHandler interface {
	Hello(context.Context, *HelloRequest, *HelloResponse) error
}

func RegisterTcpHandler(s server.Server, hdlr TcpHandler, opts ...server.HandlerOption) error {
	type tcp interface {
		Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error
	}
	type Tcp struct {
		tcp
	}
	h := &tcpHandler{hdlr}
	return s.Handle(s.NewHandler(&Tcp{h}, opts...))
}

type tcpHandler struct {
	TcpHandler
}

func (h *tcpHandler) Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error {
	return h.TcpHandler.Hello(ctx, in, out)
}
